### ISSUE TITLE
[Question] Can ClassHunter be used to find obsfucated methods?

### ISSUE THREAD

**Issue by akhilkedia** [Nordskog/ClassHunter#1]
This library is absolutely great for trying to find obsfucated classes!
But I assume there is no way to find the new (obsfucated) method name in an obsfucated class?

Say if the method had a particularly unique set of parameters/return type, I believe profiling based on params/returntype given the class should be able to automatically find that method.
But if the function has no/few params, and shares the same params with several others obsfucated functions in the same class, this library will not be able to help pick the exact function right?

(Perhaps someday this can be extended to pinpoint obsfucated functions based on call graphs, but that seems to be shooting for the stars.)

**Comment by TheRoughy** [comment]
Indeed, recognizing methods without unique signatures is outside the scope of this library.

The only alternative I know of is ProFinder, which is an external tool that recognizes classes based on strings defined there ... or something. Only good for classes, in any case.
The best approach would probably be to do some rudimentary parsing of the dex file, then generating a profile from that. I'm not going to have time to write a dex parser anytime soon though.

In the meanwhile, in my experience the order of methods returned by getDeclaredMethods() is very likely to be the same every time. The standard makes no promises about the order, and things like fields have a tendency to move all over the place,  but methods tend to stay where they are (barring any major changes to the source files, presumably). So if you have 3 methods that have identical signatures, you can often just identify which of the 3 is the right one, and always pick that from the list.

**Comment by akhilkedia** [comment]
Thanks for your reply!
The order of methods approach sound promising (ofcourse not foolproof, but still should be of help).
I will give this a try.

**Comment by akhilkedia** [comment]
For future reference for anyone - The "order of the methods" approach mentioned above does seem to work just fine. There are no guarantees ofcourse, but it seems to work ok.
